M48
; DRILL file {KiCad (6.0.0-rc1-124-g18b4ebcc17)} date Thu Nov 25 20:10:18 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-11-25T20:10:18+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-rc1-124-g18b4ebcc17)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
%
G90
G05
T1
X31.77Y-53.5
X31.77Y-56.5
T0
M30
